<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>CiyuanSha</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Build\**\*.cs" />
    <Compile Remove="CiyuanSha.GameCore\**\*.cs" />
    <Compile Remove="CiyuanSha.GameCore.Tests\**\*.cs" />
    <Compile Remove="CiyuanSha.GameCore.Simulations\**\*.cs" />
    <None Remove="Build\**\*" />
    <EmbeddedResource Remove="Build\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="CiyuanSha.GameCore\CiyuanSha.GameCore.csproj" />
  </ItemGroup>
</Project>
